<?php
// $Id$

/**
 * @file
 * This module adds a textfield to product forms for you to enter a minimum
 * quantity of the product that must be in the cart for it to be checked out.
 *
 * The product minimum checkout pane must be the lowest weighted cart pane in
 * order for the logic to properly intercept any invalid carts.
 *
 * Coded by Ryan of Ubercart.org.
 *
 * Development sponsored by Plum Drama - http://www.plumdrama.com
 */


/*******************************************************************************
 * Hook Functions (Drupal)
 ******************************************************************************/


/**
 * Implementation of hook_menu()
 */
function uc_product_min_menu() {
  $items['admin/settings/uc_product_min'] = array(
    'title' => 'min product settings',
    'description' => 'min product settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_product_min_admin_settings_form', NULL),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

function uc_product_min_admin_settings_form() {
  $form = array();

  $form['uc_product_min_group_nids'] = array(
    '#type' => 'textfield',
    '#title' => t('Group nids.'),
    '#default_value' => variable_get('uc_product_min_group_nids', '28,55,313'),
    '#size' => 20,
    '#maxlength' => 20,
    '#description' => t("List the Node ID's for the products included in the group. Separate Node ID's with a comma."),
    '#required' => TRUE,
  );
  $form['uc_product_min_group_qty'] = array(
    '#type' => 'textfield',
    '#title' => t('Group nids.'),
    '#default_value' => variable_get('uc_product_min_group_qty', '250'),
    '#size' => 3,
    '#maxlength' => 3,
    '#description' => t("List the minimum qty for the combined total of the group products."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function uc_product_min_admin() {
  $form = array();

  $form['onthisdate_maxdisp'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of links'),
    '#default_value' => variable_get('onthisdate_maxdisp', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The maximum number of links to display in the block."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_nodeapi().
 */
function uc_product_min_nodeapi(&$node, $op, $arg3 = null, $arg4 = null) {
  switch($op) {
    case 'delete':
      db_query("DELETE FROM {uc_product_min} WHERE nid = %d", $node->nid);
      break;

    case 'load':
      $result = db_query("SELECT * FROM {uc_product_min} WHERE nid = %d", $node->nid);
      if ($row = db_fetch_object($result)) {
        return array('product_min' => $row->product_min, 'pmin_multiple' => $row->pmin_multiple); 
      }
      break;

    case 'insert':
    case 'update':
      $node->product_min = intval($node->product_min);
      if ($node->product_min <= 0) {
        db_query("DELETE FROM {uc_product_min} WHERE nid = %d", $node->nid);
      }
      else {
        db_query("UPDATE {uc_product_min} SET product_min = %d, pmin_multiple = %d WHERE nid = %d", $node->product_min, $node->pmin_multiple, $node->nid);
        if (db_affected_rows() == 0) {
          db_query("INSERT INTO {uc_product_min} VALUES (%d, %d, %d)", $node->nid, $node->product_min, $node->pmin_multiple);
        }
      }
      break;

    case 'view':
      if ($node->product_min > 1) {
        drupal_add_css(drupal_get_path('module', 'uc_product_min') .'/uc_product_min.css');

        $node->content['product_min'] = array(
          '#value' => theme('uc_product_min', $node->product_min, $node->pmin_multiple),
          '#weight' => 2,
        );
      }
      break;
  }
}

/**
 * Implementation of hook_form_alter().
 */
function uc_product_min_form_alter(&$form, &$form_state, $form_id) {
  $node = $form['#node'];
  $product_types = uc_product_node_info();
  if ($form_id == $node->type .'_node_form' && isset($product_types[$node->type])){
    $form['product_min_fieldset'] = array(
      '#type' => 'fieldset',
      '#title' => t('Product minimum'),
      '#collapsed' => FALSE,
    );
    $form['product_min_fieldset']['product_min'] = array(
      '#type' => 'textfield',
      '#title' => t('Minimum quantity to checkout'),
      '#description' => t('Enter the minimum quantity of this product needed to checkout.'),
      '#default_value' => !empty($node->product_min) ? $node->product_min : 1,
    );
    $form['product_min_fieldset']['pmin_multiple'] = array(
      '#type' => 'checkbox',
      '#title' => t('Products must be purchased in multiples of the above value.'),
      '#default_value' => $node->pmin_multiple,
    );
  }
}


/*******************************************************************************
 * Hook Functions (Ubercart)
 ******************************************************************************/

/**
 * Implementation of hook_checkout_pane().
 */
function uc_product_min_checkout_pane() {
  $panes[] = array(
    'id' => 'product_min',
    'callback' => 'uc_checkout_pane_product_min',
    'title' => t('Product minimums'),
    'desc' => t('Checks a cart to make sure it meets the product minimum requirements.'),
    'weight' => -10,
  );

  return $panes;
}


/*******************************************************************************
 * Callback Functions, Forms, and Tables
 ******************************************************************************/

// Checks the cart at checkout to make sure it's valid.
function uc_checkout_pane_product_min($op) {
  switch ($op) {
    case 'view':
      $items = uc_cart_get_contents();
      $pass = TRUE;

      _uc_product_min_get_min($items);
      _uc_product_min_get_custom_min($items);

      $group_items = _uc_product_min_get_group($items);
      if ($group_items) {
        $group_item_count = count($group_items);
        if ($group_item_count < 2) {
          unset($group_item_count);
        }
      }

      $groups = array();

      foreach ($items as $item) {

        if (isset($item->multiple) && $item->multiple) {
          if ($item->qty % $item->multiple != 0) {
            drupal_set_message(t('!item must be ordered in multiples of !qty.', array('!item' => $item->title, '!qty' => $item->multiple)), 'warning');
            $pass = FALSE;
          }
        }

        if (isset($group_item_count) && isset($item->group)) {
          if (!isset($groups[$item->group])) {
            $groups[$item->group]['min'] = _uc_product_min_get_group_qty('it_works');
            $groups[$item->group]['qty'] = $item->qty;
            $groups[$item->group]['titles'] = array($item->title);
          }
          else {
            $groups[$item->group]['qty'] += $item->qty;
            $groups[$item->group]['titles'][] = $item->title;
          }
        }
        else {
          if (isset($item->min)) {
            if ($item->qty < $item->min) {
              drupal_set_message(t('You must order at least !qty of @customized !item.', array('!qty' => $item->min, '!item' => $item->title, '@customized' => $item->custom)), 'warning');
              $pass = FALSE;
              $item->pass = FALSE;
            }
          }
        }

      }

      if (count($groups)) {
        foreach($groups as $group_name => $group_info) {
          if ($group_info['qty'] < $group_info['min']) {
            $items = implode(', ', $group_info['titles']);
            drupal_set_message(t('The combined total of !items must be !qty or more.', array('!items' => $items, '!qty' => $group_info['min'])), 'warning');
            $pass = FALSE;
          }
        }
      }

      if (!$pass) {
        drupal_set_message(t('Please update your cart contents and try again.'), 'error');
        drupal_goto('cart');
      }
      break;
    // end view
  }
}


/**
 * Grab the minimum value for products in cart.
 */
function _uc_product_min_get_min(&$items) {
  $nids = array();
  foreach ($items as $id => $item) {
    $result = db_fetch_object(db_query("SELECT * FROM {uc_product_min} WHERE nid = %d", $item->nid));
    if ($result) {
      if (isset($result->product_min) && $result->product_min) {
        $items[$id]->min = $result->product_min;
      }
      if (isset($result->pmin_multiple)) {
        $items[$id]->multiple = $result->pmin_multiple;
      }
    }
  }
}

/**
 * If the product is part of a group.
 */
function _uc_product_min_get_group(&$items) {
  $group_name = variable_get('uc_product_min_group_name', 'it_works');
  $group_nids = _uc_product_min_group($group_name);
  $group_items = array();

  if ($group_nids) {
    foreach ($items as $id => $item) {
      if (in_array($item->nid, $group_nids)) {
        $items[$id]->group = $group_name;
        $group_items[] = $item->nid;
      }
    }
  }
  return $group_items;
}

/**
 * If it is a customized product.
 */
function _uc_product_min_get_custom_min(&$items) {
  foreach ($items as $id => $item) {
    $node = node_load($item->nid);
    if ($item->data['attributes'][1] == 2 && isset($node->field_customized_minimum[0]['value'])) {
      $items[$id]->min = $node->field_customized_minimum[0]['value'];
      $items[$id]->custom = t('custom');
    }
  }
}

/**
 *
 */
function _uc_product_min_get_group_qty($group_name = '') {
  return variable_get('uc_product_min_group_qty', 250);
}

/**
 *
 */
function _uc_product_min_group($name = '') {
  $group = variable_get('uc_product_min_group_nids', '28,55,313'); //30,28,313

  if ($group && is_string($group) && strpos($group, ',')) {
    $group = str_replace(' ', '', $group);
    $group = explode(',', $group);
    if (!is_array($group) || count($group) < 2) {
      $group = FALSE;
    }
  }
  else {
    $group = FALSE;
  }
  return $group;
}

// Themes the product minimum notice line on product view pages.
function theme_uc_product_min($min, $multiple) {
  if ($multiple) {
    $output = t('This product must be ordered in sets of !qty.', array('!qty' => $min));
  }
  else {
    $output = t('Must order at least !qty to checkout.', array('!qty' => $min));
  }

  return '<div class="uc_product_min">'. $output .'</div>';
}

